//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace UpdatePaymentsCom.Payments {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PaymentsSoap", Namespace="http://ukrposhta.org/Payments/")]
    public partial class Payments : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CanceledPaymentOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPaymentOperationCompleted;
        
        private System.Threading.SendOrPostCallback AutomaticReducingOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetServiceDLLOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get418VersionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Payments() {
            this.Url = global::UpdatePaymentsCom.Properties.Settings.Default.UpdatePaymentsCom_Payments_Payments;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CanceledPaymentCompletedEventHandler CanceledPaymentCompleted;
        
        /// <remarks/>
        public event GetPaymentCompletedEventHandler GetPaymentCompleted;
        
        /// <remarks/>
        public event AutomaticReducingCompletedEventHandler AutomaticReducingCompleted;
        
        /// <remarks/>
        public event GetServiceDLLCompletedEventHandler GetServiceDLLCompleted;
        
        /// <remarks/>
        public event Get418VersionCompletedEventHandler Get418VersionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ukrposhta.org/Payments/CanceledPayment", RequestNamespace="http://ukrposhta.org/Payments/", ResponseNamespace="http://ukrposhta.org/Payments/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CanceledPayment(int paymentID, string sessionID, string indexvz) {
            object[] results = this.Invoke("CanceledPayment", new object[] {
                        paymentID,
                        sessionID,
                        indexvz});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CanceledPaymentAsync(int paymentID, string sessionID, string indexvz) {
            this.CanceledPaymentAsync(paymentID, sessionID, indexvz, null);
        }
        
        /// <remarks/>
        public void CanceledPaymentAsync(int paymentID, string sessionID, string indexvz, object userState) {
            if ((this.CanceledPaymentOperationCompleted == null)) {
                this.CanceledPaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCanceledPaymentOperationCompleted);
            }
            this.InvokeAsync("CanceledPayment", new object[] {
                        paymentID,
                        sessionID,
                        indexvz}, this.CanceledPaymentOperationCompleted, userState);
        }
        
        private void OnCanceledPaymentOperationCompleted(object arg) {
            if ((this.CanceledPaymentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CanceledPaymentCompleted(this, new CanceledPaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ukrposhta.org/Payments/GetPayment", RequestNamespace="http://ukrposhta.org/Payments/", ResponseNamespace="http://ukrposhta.org/Payments/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPayment(string strPayment) {
            object[] results = this.Invoke("GetPayment", new object[] {
                        strPayment});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPaymentAsync(string strPayment) {
            this.GetPaymentAsync(strPayment, null);
        }
        
        /// <remarks/>
        public void GetPaymentAsync(string strPayment, object userState) {
            if ((this.GetPaymentOperationCompleted == null)) {
                this.GetPaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPaymentOperationCompleted);
            }
            this.InvokeAsync("GetPayment", new object[] {
                        strPayment}, this.GetPaymentOperationCompleted, userState);
        }
        
        private void OnGetPaymentOperationCompleted(object arg) {
            if ((this.GetPaymentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPaymentCompleted(this, new GetPaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ukrposhta.org/Payments/AutomaticReducing", RequestNamespace="http://ukrposhta.org/Payments/", ResponseNamespace="http://ukrposhta.org/Payments/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AutomaticReducing(string xml) {
            this.Invoke("AutomaticReducing", new object[] {
                        xml});
        }
        
        /// <remarks/>
        public void AutomaticReducingAsync(string xml) {
            this.AutomaticReducingAsync(xml, null);
        }
        
        /// <remarks/>
        public void AutomaticReducingAsync(string xml, object userState) {
            if ((this.AutomaticReducingOperationCompleted == null)) {
                this.AutomaticReducingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAutomaticReducingOperationCompleted);
            }
            this.InvokeAsync("AutomaticReducing", new object[] {
                        xml}, this.AutomaticReducingOperationCompleted, userState);
        }
        
        private void OnAutomaticReducingOperationCompleted(object arg) {
            if ((this.AutomaticReducingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AutomaticReducingCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ukrposhta.org/Payments/GetServiceDLL", RequestNamespace="http://ukrposhta.org/Payments/", ResponseNamespace="http://ukrposhta.org/Payments/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetServiceDLL() {
            object[] results = this.Invoke("GetServiceDLL", new object[0]);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GetServiceDLLAsync() {
            this.GetServiceDLLAsync(null);
        }
        
        /// <remarks/>
        public void GetServiceDLLAsync(object userState) {
            if ((this.GetServiceDLLOperationCompleted == null)) {
                this.GetServiceDLLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServiceDLLOperationCompleted);
            }
            this.InvokeAsync("GetServiceDLL", new object[0], this.GetServiceDLLOperationCompleted, userState);
        }
        
        private void OnGetServiceDLLOperationCompleted(object arg) {
            if ((this.GetServiceDLLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetServiceDLLCompleted(this, new GetServiceDLLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ukrposhta.org/Payments/Get418Version", RequestNamespace="http://ukrposhta.org/Payments/", ResponseNamespace="http://ukrposhta.org/Payments/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Get418Version() {
            object[] results = this.Invoke("Get418Version", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Get418VersionAsync() {
            this.Get418VersionAsync(null);
        }
        
        /// <remarks/>
        public void Get418VersionAsync(object userState) {
            if ((this.Get418VersionOperationCompleted == null)) {
                this.Get418VersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet418VersionOperationCompleted);
            }
            this.InvokeAsync("Get418Version", new object[0], this.Get418VersionOperationCompleted, userState);
        }
        
        private void OnGet418VersionOperationCompleted(object arg) {
            if ((this.Get418VersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get418VersionCompleted(this, new Get418VersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CanceledPaymentCompletedEventHandler(object sender, CanceledPaymentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CanceledPaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CanceledPaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetPaymentCompletedEventHandler(object sender, GetPaymentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AutomaticReducingCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetServiceDLLCompletedEventHandler(object sender, GetServiceDLLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetServiceDLLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetServiceDLLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Get418VersionCompletedEventHandler(object sender, Get418VersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get418VersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get418VersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591